const { Telegraf, Markup } = require("telegraf");
const {
  STATES,
  getSession,
  resetSession,
  setState,
  setJD,
  setResume,
} = require("./services/sessionManager");
const { downloadTelegramFile } = require("./utils/downloadTelegramFile");
const { extractTextFromBuffer } = require("./utils/extractText");
const { analyzeJdAndResume } = require("./services/analyzeService");
const { formatAnalysis } = require("./utils/formatResult");

const MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024;

// Trusted learning resources. URLs are maintained by the application,
// rather than generated by the LLM.
const COURSE_LINKS = {
  aws: "https://skillbuilder.aws/",
  docker: "https://www.docker.com/101-tutorial/",
  kubernetes: "https://kubernetes.io/docs/tutorials/",
  java: "https://dev.java/learn/",
  "spring boot": "https://spring.io/guides",
  spring: "https://spring.io/guides",
  sql: "https://www.w3schools.com/sql/",
  git: "https://git-scm.com/docs/gittutorial",
  python: "https://www.python.org/about/gettingstarted/",
  javascript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
  react: "https://react.dev/learn",
  "node.js": "https://nodejs.org/en/learn",
  nodejs: "https://nodejs.org/en/learn",
  typescript: "https://www.typescriptlang.org/docs/",
  "machine learning": "https://developers.google.com/machine-learning/crash-course",
  "deep learning": "https://www.deeplearning.ai/courses/deep-learning-specialization/",
  terraform: "https://developer.hashicorp.com/terraform/tutorials",
  "power bi": "https://learn.microsoft.com/en-us/training/powerplatform/power-bi/",
  excel: "https://support.microsoft.com/excel",
};

function welcomeMessage() {
  return (
    "👋 *Hi! Welcome to HireSense AI.*\n\n" +
    "🤖 *What is HireSense AI?*\n\n" +
    "HireSense AI compares your *Resume* with a *Job Description* and tells you how well your profile matches the role.\n\n" +
    "I can provide:\n\n" +
    "🎯 ATS Score\n" +
    "✅ Matching Skills\n" +
    "❌ Missing Skills\n" +
    "💡 Resume Improvements\n" +
    "📚 Recommended Learning Resources\n\n" +
    "You can also reuse the same resume to analyze multiple job descriptions."
  );
}

function mainButtons() {
  return Markup.inlineKeyboard([
    [Markup.button.callback("🚀 Analyze My Resume", "start_analysis")],
    [Markup.button.callback("ℹ️ How It Works", "how_it_works")],
  ]);
}

function afterAnalysisButtons() {
  return Markup.inlineKeyboard([
    [Markup.button.callback("🔄 Analyze Another JD", "another_jd")],
    [Markup.button.callback("📄 Upload New Resume", "new_resume")],
  ]);
}

function courseButtons(courses) {
  const buttons = [];
  const seen = new Set();

  for (const course of courses || []) {
    const skill = String(course.skill || "").trim();
    const key = skill.toLowerCase();
    const url = COURSE_LINKS[key];
    if (!url || seen.has(url)) continue;
    seen.add(url);
    buttons.push([Markup.button.url(`🎓 Learn ${skill}`, url)]);
  }

  return buttons;
}

function createBot(token) {
  const bot = new Telegraf(token);

  bot.start((ctx) => {
    resetSession(ctx.chat.id);
    return ctx.reply(welcomeMessage(), {
      parse_mode: "Markdown",
      ...mainButtons(),
    });
  });

  bot.help((ctx) => {
    return ctx.reply(
      "*How to use HireSense AI*\n\n" +
        "1. Upload your Resume\n" +
        "2. Send the Job Description\n" +
        "3. Get your ATS analysis\n\n" +
        "After an analysis, you can reuse the same resume for another JD.\n\n" +
        "Send /cancel anytime to start over.",
      { parse_mode: "Markdown", ...mainButtons() }
    );
  });

  bot.command("cancel", (ctx) => {
    resetSession(ctx.chat.id);
    return ctx.reply("Cancelled. Send /start or /analyze to begin again.");
  });

  bot.command("analyze", (ctx) => {
    resetSession(ctx.chat.id);
    setState(ctx.chat.id, STATES.AWAITING_JD);
    return ctx.reply(
      "📋 Please send the *Job Description* — as text, or upload a .pdf/.docx file.",
      { parse_mode: "Markdown" }
    );
  });

  // Welcome / conversational messages
  bot.on("text", async (ctx) => {
    const chatId = ctx.chat.id;
    const session = getSession(chatId);
    const text = ctx.message.text.trim();
    const lower = text.toLowerCase();

    if (text.startsWith("/")) return;

    if (session.state === STATES.IDLE && /^(hi|hello|hey|hii|hai|start)$/i.test(lower)) {
      return ctx.reply(welcomeMessage(), {
        parse_mode: "Markdown",
        ...mainButtons(),
      });
    }

    // Same resume: after an analysis, a new JD can be sent directly.
    if (session.state === STATES.READY && session.resumeText) {
      if (text.length < 30) {
        return ctx.reply("Please send the full Job Description (at least 30 characters).");
      }
      setJD(chatId, text);
      return runAnalysis(ctx, chatId);
    }

    if (session.state === STATES.AWAITING_JD) {
      if (text.length < 30) {
        return ctx.reply(
          "That looks too short for a job description. Please paste the full JD text, or upload it as a file."
        );
      }
      setJD(chatId, text);
      setState(chatId, STATES.AWAITING_RESUME);
      return ctx.reply(
        "✅ Got the JD.\n\n📄 Now upload your *Resume* (.pdf or .docx).",
        { parse_mode: "Markdown" }
      );
    }

    if (session.state === STATES.AWAITING_RESUME) {
      return ctx.reply(
        "Please upload your resume as a *file* (.pdf or .docx) rather than pasting text.",
        { parse_mode: "Markdown" }
      );
    }

    return ctx.reply(welcomeMessage(), {
      parse_mode: "Markdown",
      ...mainButtons(),
    });
  });

  bot.on("callback_query", async (ctx) => {
    const chatId = ctx.chat.id;
    const action = ctx.callbackQuery.data;
    await ctx.answerCbQuery();

    if (action === "start_analysis") {
      const session = getSession(chatId);
      if (session.resumeText) {
        setState(chatId, STATES.READY);
        return ctx.reply("📄 Your resume is already saved. Send the Job Description to analyze it.");
      }
      resetSession(chatId);
      setState(chatId, STATES.AWAITING_JD);
      return ctx.reply("📋 Send the *Job Description* first — paste the text or upload a file.", {
        parse_mode: "Markdown",
      });
    }

    if (action === "how_it_works") {
      return ctx.reply(
        "🔍 *HOW IT WORKS*\n\n" +
          "1️⃣ Upload your Resume\n" +
          "2️⃣ Send the Job Description\n" +
          "3️⃣ AI compares both\n" +
          "4️⃣ We calculate your ATS score\n" +
          "5️⃣ We identify skill gaps\n" +
          "6️⃣ We suggest resume improvements\n" +
          "7️⃣ We recommend learning resources\n\n" +
          "Your resume can then be reused for multiple job descriptions.",
        { parse_mode: "Markdown", ...mainButtons() }
      );
    }

    if (action === "another_jd") {
      const session = getSession(chatId);
      if (!session.resumeText) {
        resetSession(chatId);
        setState(chatId, STATES.AWAITING_JD);
        return ctx.reply("Please upload your resume first.");
      }
      setState(chatId, STATES.READY);
      return ctx.reply("🔄 Great! I'll use your existing resume.\n\n📋 Send the new Job Description.");
    }

    if (action === "new_resume") {
      resetSession(chatId);
      setState(chatId, STATES.AWAITING_JD);
      return ctx.reply("📋 Send the new Job Description first. Then upload your new Resume.");
    }
  });

  bot.on("document", async (ctx) => {
    const chatId = ctx.chat.id;
    const session = getSession(chatId);
    const doc = ctx.message.document;

    if (session.state !== STATES.AWAITING_JD && session.state !== STATES.AWAITING_RESUME) {
      if (session.state === STATES.READY && session.resumeText) {
        return ctx.reply("Your resume is already saved. Please send the new Job Description as text, or click 🔄 Analyze Another JD.");
      }
      return ctx.reply("Send /analyze or /start first to begin an analysis.");
    }

    if (doc.file_size && doc.file_size > MAX_FILE_SIZE_BYTES) {
      return ctx.reply("That file is too large. Please upload a file under 5MB.");
    }

    const fileName = doc.file_name || "";
    if (!/\.(pdf|docx|txt)$/i.test(fileName)) {
      return ctx.reply("Please upload a .pdf, .docx, or .txt file.");
    }

    const label = session.state === STATES.AWAITING_JD ? "Job Description" : "Resume";

    try {
      await ctx.reply(`⏳ Processing your ${label}...`);
      const { buffer } = await downloadTelegramFile(bot, doc.file_id, fileName);
      const text = await extractTextFromBuffer(buffer, fileName);

      if (!text || text.length < 30) {
        return ctx.reply(`Couldn't extract enough readable text from that ${label}. Try a different file.`);
      }

      if (session.state === STATES.AWAITING_JD) {
        setJD(chatId, text);
        setState(chatId, STATES.AWAITING_RESUME);
        return ctx.reply(
          "✅ Got the JD.\n\n📄 Now upload your *Resume* (.pdf or .docx).",
          { parse_mode: "Markdown" }
        );
      }

      setResume(chatId, text);
      return runAnalysis(ctx, chatId);
    } catch (err) {
      console.error(`Error processing ${label}:`, err);
      return ctx.reply(`❌ Failed to process that ${label}: ${err.message}`);
    }
  });

  return bot;
}

async function runAnalysis(ctx, chatId) {
  const session = getSession(chatId);
  await ctx.reply("🔍 Analyzing JD vs Resume — this takes a few seconds...");

  try {
    const result = await analyzeJdAndResume(session.jdText, session.resumeText);
    const messages = formatAnalysis(result);

    for (const msg of messages) {
      await ctx.reply(msg, { parse_mode: "Markdown" });
    }

    const buttons = courseButtons(result.courses_to_learn);
    if (buttons.length) {
      await ctx.reply(
        "📚 *Direct Learning Links*\nClick a button to start learning:",
        { parse_mode: "Markdown", ...Markup.inlineKeyboard(buttons) }
      );
    }

    await ctx.reply(
      "Your resume is saved. You can now analyze another JD without uploading it again.",
      afterAnalysisButtons()
    );

    // Keep resume; clear only the JD and mark session ready for another JD.
    setJD(chatId, null);
    setState(chatId, STATES.READY);
  } catch (err) {
    console.error("Analysis error:", err);
    await ctx.reply("❌ Something went wrong during analysis. Your resume is still saved. Please send the JD again.");
    setState(chatId, STATES.READY);
  }
}

module.exports = { createBot };
